image: registry.gitlab.com/kodality/gitlab-builders/ng

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
      - node_modules

stages:
  - build
  - release

build:
  stage: build
  extends: .dependencies_cache
  script:
    - echo $CI_COMMIT_REF_NAME | grep -P '^\d*\.\d*\.\d*$' && npm version $CI_COMMIT_REF_NAME
    - npm install --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - "**/dist"
    expire_in: 1 hour
  only:
    - branches
    - tags

